### ISSUE TITLE
Отображение скриншота на всех секциях страницы

### ISSUE THREAD

**Issue by chernyshovmaksim** [efiand/pineglade-pp#2]
Приветствую, как можно сделать так что бы инструмент срабатывал на всю высоту страницы? На данный момент у меня срабатывает только на первую секцию.
![Скриншот проблемы](https://user-images.githubusercontent.com/8769580/208039616-a0957021-bc96-468c-9b66-c2a4a37af64f.png)

**Comment by efiand** [comment]
Добрый день. по скриншоту трудно судить, но похоже на то, что высота блока, которому задана логика проверки пиксель перфект, такая и есть, а остальное из него вываливается. Предположу, что у вас

```css
html,
body {
  height: 100%;
}
```

и содержимое просто вываливается из body. Если требуется sticky footer, можно те стили поменять на современное

```css
body {
  min-height: 100vh;
}
```

Либо, если у вас есть внутри body враппер для шапки, основной части и подвала, можно указать в опции `selector` класс этого враппера, как [здесь](https://github.com/efiand/gulp-template/blob/main/src/scripts/entries/dev.js#L8).

**Comment by chernyshovmaksim** [comment]
```css
body {
  min-height: 100vh;
}
```
сработало, спасибо **большое**
